baseURL = 'https://jo-qu.com'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'jo-qu.com'
theme = 'hugo-blog-awesome'

[params]
  goToTop = true

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    contentDir = 'content'
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = 'about'
        name = 'About Myself'
        url = '/about/'
        weight = 2
      [[languages.en.menu.main]]
        identifier = 'other-projects'
        name = 'Projects'
        url = '/other-projects/'
        weight = 3
  [languages.nl]
    languageName = 'Nederlands'
    weight = 2
    contentDir = 'content'
    [languages.nl.menu]
      [[languages.nl.menu.main]]
        identifier = 'about'
        name = 'Over Mij'
        url = '/nl/about/'
        weight = 2
      [[languages.nl.menu.main]]
        identifier = 'other-projects'
        name = 'Projecten'
        url = '/nl/other-projects/'
        weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true